### PR TITLE
(chore): Add packaging for Meteor.js

### PR DESCRIPTION
**Pull request by Urigo**
Hi @michaelbromley

I'm a package maintainer for [Meteor.js](https://www.meteor.com/), a popular full-stack JavaScript framework.

I'm also the creator of [angular-meteor](http://angularjs.meteor.com/), a library that let's you work with AngularJS on top of Meteor.

I use angularUtils-pagination on our [tutorial](http://angularjs.meteor.com/tutorial/step_12).
Until now I've been publishing your library to Meteor myself but I think it is better you add an official Meteor release as a lot of users use that.

This PR will allow you to directly publish updated versions of angularUtils-pagination as they become available. 
All you have to do is create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and I'll add you as the owner of the angularUtils organization there (or you can create it under your username or a different organization, whatever you want).

I've already published the current version of the [package on Atmosphere](https://atmospherejs.com/angularutils/pagination) (Meteor's package directory).

If you use Grunt or Gulp as part of your release, there are prepared tasks for publishing to Meteor here:
https://github.com/MeteorPackaging/grunt-gulp-meteor

Thanks & best regards,
Uri

### CODE REVIEW

**Comment by Urigo** [comment]
@michaelbromley in order to release those version to Atmosphere, you will also need to run `meteor publish` in the command line.
Right now, the current version in Atmosphere is 0.7.0 - https://atmospherejs.com/angularutils/pagination

**Comment by michaelbromley** [comment]
@Urigo Hi, so I installed the Meteor CLI and then ran `meteor publish` from my local copy of this repo, but I got:

```
=> Errors while publishing:

While pre-publishing package angularutils:pagination:
error: You are not an authorized maintainer for this package.
```

Any idea what is wrong here?

**Comment by Urigo** [comment]
Great! Just give me your Meteor username and I'll add you to the package.
Then you can do the same and it will work

**Comment by michaelbromley** [comment]
sure: michaelbromley

**Comment by Urigo** [comment]
ok, can you try now?

**Comment by michaelbromley** [comment]
Done, and it worked! Good timing - I just pushed a new minor release (0.9.0) this morning :+1:

**Comment by Urigo** [comment]
Awesome!  welcome to the Meteor package managers community :+1:

**Pull request merged**
